name: First Workflow
on: [push]

jobs:
  run-simple-commands:
      runs-on: ubuntu-latest
      steps:
        - name: print Hello World
          run: echo "Hello World"
        - name: Run simple commands
          run: |
            node -v
            npm -v
  parallel_job:
      runs-on: macos-latest
      steps:
          - name: Log Software version
            run: sw_vers
  dependent_job:
      runs-on: windows-latest
      needs: run-simple-commands
      steps:
          - name: Log Software version
            run: Write-Output Get-ComputerInfo
          - name: Error bit
            run: doesnot existss
