name: First Workflow
on: [push]
jobs:
  simple-run-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
      - name: Node & npm version
        run: |
          node -v
          npm -v
  parallel_job:
    runs-on: ubuntu-latest
    steps:
      - name: Get Git version
        run: git --version
  dependent_job:
    needs: simple-run-commands
    runs-on: ubuntu-latest
    steps:
      - name: Get redis version
        run: redis --version
