name: Third Workflow
on: [push]
jobs:
    display_working_directory:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory and list files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_WORKSPACE
                echo $GITHUB_REPOSITORY
    display_working_directory_windows:
        runs-on: windows-latest
        steps:
            - name: Display working directory and list files
              run: |
                pwd
                ls
                echo $GITHUB_SHA
                echo $GITHUB_WORKSPACE
                echo $GITHUB_REPOSITORY

