name: Second Workflow
on: [push]
jobs:
  workflow_commands:
    runs-on: ubuntu-latest
    steps:
      - name: Error
        run: echo "::error::Missing Parameters"
      - name: Error with params
        run: echo "::error title=Error title,line=2,endLine=3,col=4,endColumn=7::Missing Params"
      - name: Warning with params
        run: echo "::warning title=Warning title,line=2,endLine=3,col=4,endColumn=7::Missing Params"
      - name: Debug with params
        run: echo "::debug title=Debug title,line=2,endLine=3,col=4,endColumn=7::Missing Params"
      - name: Notice with params
        run: echo "::notice title=Notice title,line=2,endLine=3,col=4,endColumn=7::Missing Params"
      - name: My Second Group
        run: |
          echo "::group::My Group"
          echo "Insie group"
          echo "::endgroup"
      - name: Masking
        run: |
          echo "::add-mask:niniko"
      - name: Log mask
        run: echo "niniko"
