name: Workflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
        - name: Set error message
          run: echo "::error::Missing semicolon"
        - name: Set error message with param
          run: echo "::error title=Error title,file=app.js,line=2,endLine=3,col=4,endColumn=7::Missing semicolon"
        - name: Set debug message with param
          run: echo "::debug title=Debug title,file=app.js,line=2,endLine=3,col=4,endColumn=7::Missing semicolon"
        - name: Set warning message with param
          run: echo "::warning title=Warning title,file=app.js,line=2,endLine=3,col=4,endColumn=7::Missing semicolon"
        - name: Set notice message with param
          run: echo "::notice title=Notice title,file=app.js,line=2,endLine=3,col=4,endColumn=7::Missing semicolon"
        - name: Add group message
          run: |
           echo "::group::My Group"
           echo "Inside group"
           echo "::endgroup::"
        - name: add mask message
          run: echo "::add-mask::Set secret"
        - name: log secret
          run: echo "Set secret"
        
